name = "LearningAbstractions"
uuid = "4069ee2e-21bd-44c6-a901-be9d81182ece"
authors = ["John Jackson", "University of Colorado Boulder"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
